# https://github.com/rust-lang/cargo/issues/1634#issuecomment-1224091272
[env]
RUST_BACKTRACE = "1"

LIBSQLITE3_FLAGS = { value = "-DSQLITE_ENABLE_MATH_FUNCTIONS SQLITE_ENABLE_EXPLAIN_COMMENTS SQLITE_ENABLE_FTS3_TOKENIZER SQLITE_ENABLE_FTS4 SQLITE_ENABLE_OFFSET_SQL_FUNC SQLITE_ENABLE_UNKNOWN_SQL_FUNCTION SQLITE_ENABLE_UPDATE_DELETE_LIMIT", force = true }

[target.x86_64-unknown-linux-musl]
rustflags = ["-C", "target-feature=+crt-static"]

[target.aarch64-unknown-linux-musl]
rustflags = [
    "-C", "target-feature=+crt-static",

    # https://github.com/rust-lang/rust/issues/89626#issuecomment-1686073426
    "-C", "link-arg=-lc",
]

# Don't statically link glibc as it's LGPL