name: CI

on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
      - run: sudo apt install -y libsqlite3-mod-spatialite
      - run: cargo test --features sqlite
      - run: cargo test --features sqlcipher

  build-win32:
    needs: test
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - target: x86_64-pc-windows-msvc
            vsce_target: win32-x64
          - target: i686-pc-windows-msvc
            vsce_target: win32-ia32
          - target: aarch64-pc-windows-msvc
            vsce_target: win32-arm64
    steps:
      - uses: actions/checkout@v1
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          targets: ${{ matrix.target }}
      - run: |
          $ErrorActionPreference = "Stop"

          rustup target add ${{ matrix.target }}
          cargo build --release --features sqlite --target ${{ matrix.target }}
          cp target/${{ matrix.target }}/release/db-driver-rs.exe db-driver-${{ matrix.vsce_target }}.exe
      - uses: softprops/action-gh-release@v1
        with:
          files: 'db-driver-*'
          name: 'release'
          tag_name: 'draft'
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-linux:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            vsce_target: linux-x64-gnu
          - target: x86_64-unknown-linux-musl
            vsce_target: linux-x64-musl
          - target: aarch64-unknown-linux-gnu
            vsce_target: linux-arm64-gnu
          - target: aarch64-unknown-linux-musl
            vsce_target: linux-arm64-musl
          - target: armv7-unknown-linux-gnueabihf
            vsce_target: linux-arm-gnu
    steps:
      - uses: actions/checkout@v1
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          targets: ${{ matrix.target }}
      - run: cargo install cross --git https://github.com/cross-rs/cross
      - run: |
          set -xEeuo pipefail

          # https://github.com/cross-rs/cross/wiki/FAQ#exec-format-error
          docker run --privileged --rm tonistiigi/binfmt --install all

          rustup override set nightly
          rustup update
          cross build --release --features sqlite --target ${{ matrix.target }}
          cp target/${{ matrix.target }}/release/db-driver-rs db-driver-${{ matrix.vsce_target }}
        shell: bash
      - uses: softprops/action-gh-release@v1
        with:
          files: 'db-driver-*'
          name: 'release'
          tag_name: 'draft'
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-darwin:
    needs: test
    runs-on: macos-latest
    strategy:
      matrix:
        include:
          - target: x86_64-apple-darwin
            vsce_target: darwin-x64
          - target: aarch64-apple-darwin
            vsce_target: darwin-arm64
    steps:
      - uses: actions/checkout@v1
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          targets: ${{ matrix.target }}
      - run: |
          set -xEeuo pipefail

          cargo build --release --features sqlite --target ${{ matrix.target }}
          cp target/${{ matrix.target }}/release/db-driver-rs db-driver-${{ matrix.vsce_target }}
        shell: bash
      - uses: softprops/action-gh-release@v1
        with:
          files: 'db-driver-*'
          name: 'release'
          tag_name: 'draft'
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
